AWSTemplateFormatVersion: '2010-09-09'
Description: 'PQC Secure Transfer Monitoring Stack'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, staging, prod]
  
  ECSClusterName:
    Type: String
    Description: Name of the ECS cluster to monitor

Resources:
  # CloudWatch Dashboard
  PQCDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub pqc-secure-transfer-${Environment}
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "properties": {
                "metrics": [
                  ["AWS/ECS", "CPUUtilization", "ServiceName", "pqc-secure-transfer-${Environment}", "ClusterName", "${ECSClusterName}"],
                  [".", "MemoryUtilization", ".", ".", ".", "."]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}",
                "title": "ECS Service Metrics"
              }
            }
          ]
        }

  # CloudWatch Alarms
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub pqc-high-cpu-${Environment}
      AlarmDescription: High CPU utilization
      MetricName: CPUUtilization
      Namespace: AWS/ECS
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: ServiceName
          Value: !Sub pqc-secure-transfer-${Environment}
        - Name: ClusterName
          Value: !Ref ECSClusterName

Outputs:
  DashboardURL:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${PQCDashboard}